name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_gradient: ^0.0.2+1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  args: ^2.4.0
  crypto: ^3.0.0
  dart_flutter_team_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assests/images/quiz-logo.png
